[package]
name = "teggle-omnibus-core"
version = "0.10.0"
authors = ["David Radunz <david@vimturian.ltd>", "Ethan Frey <ethanfrey@users.noreply.github.com>", "SCRT Labs <info@scrtlabs.com>"]
edition = "2018"
description = "Core library for building Omnibus smart contracts"
repository = "https://github.com/teggle-io/teggle-omnibus/tree/master/packages/core"
license = "Apache-2.0"
readme = "README.md"

[features]
default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
debug-print = ["cosmwasm-std/debug-print"]
test-print = []

[dependencies]
cosmwasm-std = { version = "0.10", package = "teggle-cosmwasm-std", features = ["rc-deps"], path = "../cosmwasm/std" }

[dependencies.zip-module-resolver]
package = "teggle-rhai-module-resolver-zip"
features = [ "json_config" ]
path = "../rhai/module-resolver/zip"

[dependencies.rhai]
#version = "1.6.1"
#git = "https://github.com/schungx/rhai"
features = [ "only_i32", "no_float", "no_position", "no_closure", "unchecked", "internals" ]
path = "../../../rhai"